### ISSUE TITLE
"Stop Print" enables all motors

### ISSUE THREAD

**Issue by BBStephan** [PodoPrinter/Marlin#1]
**Application Version**
1.1.8

**Steps to Reproduce**
Select "Stop Print"

**Actual Results**
Printer stops, all motors enable.

**Expected results**
Motors should disable.
If possible, the belt should turn a bit to move the print away from the heated zone.

**Additional Information**

**Comment by fieldOfView** [comment]
Seems fixed in 1.1.9 branch
