### ISSUE TITLE
"Pause Print" - Parking position

### ISSUE THREAD

**Issue by BBStephan** [PodoPrinter/Marlin#2]
**Application Version**
1.1.8

**Steps to Reproduce**
Select "Pause Print" during a print

**Actual Results**
Printer stops moving, creating a molten spot at the product

**Expected results**
It should better move to a parking position, like e.g. X0 Y2

**Additional Information**

**Comment by fieldOfView** [comment]
It seems that this is working in the bb-1.1.9 branch, provided that the printer is homed. If the printer is not fully homed, it will not park. I will see what I can do about that.

**Comment by fieldOfView** [comment]
I am now making sure the printer is homed, even if the gcode only homes the x-axis.
