### ISSUE TITLE
Y limitation bug

### ISSUE THREAD

**Issue by BBStephan** [PodoPrinter/Marlin#3]
**Application Version**
1.1.5, 1.1.8

**Steps to Reproduce**
Hard to reproduce. It seems to occur randomly.

**Actual Results**
Machine does not exceed random Y heigths.
Restarting the sane gcode fixes the issue.

**Expected results**
Machine does not exceed the maximum Y heigt

**Additional Information**

![cesar](https://user-images.githubusercontent.com/32984892/44454198-2de29b00-a5fb-11e8-992c-8026a584699b.jpg)

**Comment by fieldOfView** [comment]
Sorry, can you elaborate?

Does the printer "act as if" it hits the Y limit switch? This could be related to the fact that we don't do a "true" homing, so Marlin gets confused where Y0 really is.

**Comment by BBStephan** [comment]
The machine prints fine what's under a certain Y height.
It basically cuts off the model at a certain height and over extrudes on that cutting plane.

I think that when a machine hits a Y limit switch during the print, it continue printing with an offset (looks like skipping steps), which is not the case here.

**Comment by fieldOfView** [comment]
I think Marlin is hitting the "software" limit, ie the same limit that disallows the belt from going further back than when the printer was turned on.

**Comment by BBStephan** [comment]
I will try if commenting `#define MAX_SOFTWARE_ENDSTOP_Y` will fix this!

**Comment by BBStephan** [comment]
Works great so far!

**Comment by fieldOfView** [comment]
Seems to be fixed
