### ISSUE TITLE
Y homing vibrations

### ISSUE THREAD

**Issue by BBStephan** [PodoPrinter/Marlin#4]
**Application Version**
1.1.9

**Printer**
BLACKBELT 3D Printer

**Steps to Reproduce**
Start up any print

**Actual Results**
After the first home of the X axis, the Y axis moves with low power into the belt, causing vibrations.
Those have resulted in some loose print heads.

**Expected results**
Homing should occur with less or no vibrations.

**Additional Information**
I'd like to test different homing procedures.
Where can I change those in the firmware?

**Comment by fieldOfView** [comment]
The homing is implemented in Marlin_main.cpp, here: https://github.com/BlackBelt3D/Marlin/commit/e3534af24544fa98ce9422ff30c38d1e168dd6a8#diff-1cb08de130a6ece2d1b5b9c37bcfef48R3097

Line 3108/3109 set the low torque for the homing. If you make the number lower, you get less vibrations, but if you make it too low the y axis may not move at all. Perhaps I should oil my y axis though so a lower torque can be used.
